"""initial schema

Revision ID: db0f78ecb787
Revises: 
Create Date: 2026-08-11 15:21:30.950575

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'db0f78ecb787'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('total_photos', sa.Integer(), nullable=False),
    sa.Column('processed_photos', sa.Integer(), nullable=False),
    sa.Column('failed_photos', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lightroom_id', sa.String(), nullable=True),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('preview_path', sa.String(), nullable=True),
    sa.Column('capture_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_mtime', sa.Float(), nullable=False),
    sa.Column('is_virtual_copy', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('existing_rating', sa.Integer(), nullable=True),
    sa.Column('existing_color_label', sa.String(), nullable=True),
    sa.Column('existing_pick_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_lightroom_id'), 'photos', ['lightroom_id'], unique=True)
    op.create_index(op.f('ix_photos_original_path'), 'photos', ['original_path'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('perceptual_hash', sa.String(), nullable=False),
    sa.Column('sharpness_score', sa.Float(), nullable=False),
    sa.Column('blur_confidence', sa.Float(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('highlight_clipping', sa.Float(), nullable=False),
    sa.Column('shadow_clipping', sa.Float(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_file_hash'), 'analyses', ['file_hash'], unique=False)
    op.create_index(op.f('ix_analyses_fingerprint'), 'analyses', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_analyses_perceptual_hash'), 'analyses', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_analyses_photo_id'), 'analyses', ['photo_id'], unique=True)
    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.Enum('EXACT_DUPLICATE', 'NEAR_DUPLICATE', 'BURST', name='grouptype'), nullable=False),
    sa.Column('analysis_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_groups_group_type'), 'duplicate_groups', ['group_type'], unique=False)
    op.create_table('prepared_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('ADD_TO_REVIEW_COLLECTION', 'SET_PLUGIN_METADATA', name='actiontype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'APPLIED', 'UNDONE', 'REJECTED', name='actionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepared_actions_batch_id'), 'prepared_actions', ['batch_id'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prepared_action_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Enum('CREATED', 'CONFIRMED', 'APPLIED', 'UNDONE', 'FAILED', name='actionevent'), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prepared_action_id'], ['prepared_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('keeper_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('KEEPER', 'REVIEW', 'LIKELY_REDUNDANT', name='recommendation'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'photo_id', name='uq_group_photo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_prepared_actions_batch_id'), table_name='prepared_actions')
    op.drop_table('prepared_actions')
    op.drop_index(op.f('ix_duplicate_groups_group_type'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    op.drop_index(op.f('ix_analyses_photo_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_perceptual_hash'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_fingerprint'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_file_hash'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_photos_original_path'), table_name='photos')
    op.drop_index(op.f('ix_photos_lightroom_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
